### ISSUE TITLE
Your module is not compatible with es5

### ISSUE THREAD

**Issue by fallenleavesguy** [vladzadvorny/http-build-query#2]
Your module is not compatible with es5 !!!

**Comment by vladzadvorny** [comment]
@yeluoqiuzhi  why do you think so?

**Comment by fallenleavesguy** [comment]
Because you use es6 syntax without any compiler

**Comment by vladzadvorny** [comment]
what version node.js you using? 
it only works: 
`  "engines": {
    "node": ">=4.0.0"
  }`

**Comment by fallenleavesguy** [comment]
I use it in old browser. And I compile it with webpack, the uglifyJs in webpack doesn't support es6 syntax

**Comment by vladzadvorny** [comment]
I understood. well, I'll fix it in the evening

**Comment by fallenleavesguy** [comment]
Ok.Thank you. I have forked it, and write in syntax in es5

[I forked it](https://github.com/dz-web/http-build-query/blob/master/index.js)
