### ISSUE TITLE
Empty values aren't parsed correctly

### ISSUE THREAD

**Issue by d42ohpaz** [vladzadvorny/http-build-query#3]
Running `http-build-query@0.6.0`, when a parameter has an empty value (`''` or `null`), the function will not provide the expected `key=` value, and instead return the equivalent of an empty string for the key/value pair. 

For example, if I pass `{key1: '', key2: ''}` to `httpBuildQuery`, I will get back `&` as the parsed query string instead of the expected `key1=&key2=` query string.

This is contrary to how PHP works:

```
Psy Shell v0.9.3 (PHP 7.2.4 — cli) by Justin Hileman
>>> http_build_query(['key1' => '', 'key2' => '']);
=> "key1=&key2="
>>> 
```

**Comment by vladzadvorny** [comment]
Thank you! I fixed it 😊
